## 1
name: Upload thing when pushing something

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK environment to 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      # 3
      - name: Generate Release APK
        run: ./gradlew android:assembleRelease
      - name: Generate Release JAR
        run: ./gradlew desktop:release
      # 4
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: android/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.2"

      - name: Upload as Pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Developer Build"
          files: |
              android/build/outputs/apk/release/android-release-unsigned-signed.apk
              desktop/build/libs/*.jar

      - name: Remove unsigned apk
        run: rm android/build/outputs/apk/release/android-release-unsigned.apk

      - name: Remove unsigned apk
        run: rm android/build/outputs/apk/release/android-release-unsigned-aligned.apk

      - name: Remove signing key
        run: rm android/build/outputs/apk/release/signingKey.jks

      - name: Rename APK
        run: mv android/build/outputs/apk/release/android-release-unsigned-signed.apk android/build/outputs/apk/release/android-release.apk
